### ISSUE TITLE
Fautes d'orthographe

### ISSUE THREAD

**Issue by niahoo** [xDEADC0DE/ballot-fr#11]
« S'il y a un candidat qui bas » => « S'il y a un candidat qui **bat** »

**Comment by niahoo** [comment]
« Bon, s'en est fini » => « Bon, **c'en** est fini »

**Comment by xDEADC0DE** [comment]
Bien vu ! Je peux les modifier si tu préfère.

**Comment by niahoo** [comment]
Je t'ai fait une PR, maintenant que je sais quel sur quel repo il faut le faire ;)
