### ISSUE TITLE
Repo officiel

### ISSUE THREAD

**Issue by niahoo** [xDEADC0DE/ballot-fr#12]
Hello, 

Je voulais forker pour corriger la faute que je viens de créer, mais le bandeau "Fork me" ramène ici, tandis que le lien "officiel" en bas de page renvoie vers borisschapira/ballot-fr.

Quel est le repository officiel ?

**Comment by xDEADC0DE** [comment]
Bonjour, normalement c'est celui-ci le plus à jour, je corrigerai le len en bas de page.

**Comment by xDEADC0DE** [comment]
Voilà, j'ai changé le lien.

**Comment by niahoo** [comment]
Super merci :)
