### ISSUE TITLE
Mettre à jour avec le dépôt d’origine

### ISSUE THREAD

**Issue by xDEADC0DE** [xDEADC0DE/ballot-fr#14]
@ncase a mis à jour son index.html depuis que Trudeau a renoncé à reformer le système électoral canadien : https://www.theguardian.com/world/2017/feb/01/justin-trudeau-abandons-voter-reform-canada (février 2017)

Modifications traduites en français et intégrées ici.

**Comment by xDEADC0DE** [comment]
Fixed by a5b64f9b0ddb52df37304a9647e3a0442c7a455e

**Comment by borisschapira** [comment]
Merci
