### ISSUE TITLE
Problème CSS (?) dans le bac à sable

### ISSUE THREAD

**Issue by xDEADC0DE** [xDEADC0DE/ballot-fr#15]
![ballot-fr-wtf](https://user-images.githubusercontent.com/1249572/73140315-ed047680-4077-11ea-8a2b-42138b025582.png)

**Comment by borisschapira** [comment]
Je dirais que dans certains navigateur modernes, `text-decoration-skip-ink` est activé par défaut, ce qui fait que le soulignement disparait sous les lettres qui descendent "trop bas".

Si on le désactive avec :

```
abbr[title] {
	text-decoration-skip-ink: none;
}
```

On obtient : 

![Capture d’écran 2020-01-27 à 09 23 20](https://user-images.githubusercontent.com/284742/73159499-e8c37200-40e6-11ea-9573-c8cd7ec8cc5b.png)

Autre possibilité, contrôler la hauteur de ce soulignement (CSS 3) :

```
abbr[title] {
	text-underline-position: under;
}
```

On obtient alors : 

![Capture d’écran 2020-01-27 à 09 23 27](https://user-images.githubusercontent.com/284742/73159541-0690d700-40e7-11ea-8a6c-f4cf5e129e08.png)

J'ai une préférence pour cette seconde possibilité. Qu'en penses-tu ?

**Comment by xDEADC0DE** [comment]
Le 2e à l’air mieux en effet.
J’essaye de corriger ça dans les jours qui viennent.

**Comment by xDEADC0DE** [comment]
Lié à #17 ? Ce problème de sous-titre n’apparait pas sur la version originale : 
https://ncase.me/ballot/sandbox/
